/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { IntunedClientError } from "./intunedclienterror.js";

/**
 * The requested resource was not found
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#not-found} - Find more info here
 */
export const GetJobsProjectJobsCode = {
  NotFound: "not-found",
} as const;
/**
 * The requested resource was not found
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#not-found} - Find more info here
 */
export type GetJobsProjectJobsCode = ClosedEnum<typeof GetJobsProjectJobsCode>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const GetJobsProjectJobsCategory = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type GetJobsProjectJobsCategory = ClosedEnum<
  typeof GetJobsProjectJobsCategory
>;

/**
 * Not Found
 */
export type GetJobsProjectJobsResponseResponseBodyData = {
  /**
   * The requested resource was not found
   */
  code: GetJobsProjectJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: GetJobsProjectJobsCategory;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Not Found
 */
export class GetJobsProjectJobsResponseResponseBody extends IntunedClientError {
  /**
   * The requested resource was not found
   */
  code: GetJobsProjectJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: GetJobsProjectJobsCategory;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: GetJobsProjectJobsResponseResponseBodyData;

  constructor(
    err: GetJobsProjectJobsResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "GetJobsProjectJobsResponseResponseBody";
  }
}

/**
 * The request requires user authentication
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#unauthorized} - Find more info here
 */
export const GetJobsCode = {
  Unauthorized: "unauthorized",
} as const;
/**
 * The request requires user authentication
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#unauthorized} - Find more info here
 */
export type GetJobsCode = ClosedEnum<typeof GetJobsCode>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const GetJobsCategory = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type GetJobsCategory = ClosedEnum<typeof GetJobsCategory>;

/**
 * Unauthorized
 */
export type GetJobsProjectJobsResponseBodyData = {
  /**
   * The request requires user authentication
   */
  code: GetJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: GetJobsCategory;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Unauthorized
 */
export class GetJobsProjectJobsResponseBody extends IntunedClientError {
  /**
   * The request requires user authentication
   */
  code: GetJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: GetJobsCategory;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: GetJobsProjectJobsResponseBodyData;

  constructor(
    err: GetJobsProjectJobsResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "GetJobsProjectJobsResponseBody";
  }
}

/**
 * The request is invalid or malformed
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#bad-request} - Find more info here
 */
export const Code = {
  BadRequest: "bad-request",
} as const;
/**
 * The request is invalid or malformed
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#bad-request} - Find more info here
 */
export type Code = ClosedEnum<typeof Code>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const Category = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type Category = ClosedEnum<typeof Category>;

/**
 * Bad Request
 */
export type GetJobsResponseBodyData = {
  /**
   * The request is invalid or malformed
   */
  code: Code;
  /**
   * Errors caused by user actions or input
   */
  category: Category;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Bad Request
 */
export class GetJobsResponseBody extends IntunedClientError {
  /**
   * The request is invalid or malformed
   */
  code: Code;
  /**
   * Errors caused by user actions or input
   */
  category: Category;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: GetJobsResponseBodyData;

  constructor(
    err: GetJobsResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "GetJobsResponseBody";
  }
}

/** @internal */
export const GetJobsProjectJobsCode$inboundSchema: z.ZodNativeEnum<
  typeof GetJobsProjectJobsCode
> = z.nativeEnum(GetJobsProjectJobsCode);

/** @internal */
export const GetJobsProjectJobsCode$outboundSchema: z.ZodNativeEnum<
  typeof GetJobsProjectJobsCode
> = GetJobsProjectJobsCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsProjectJobsCode$ {
  /** @deprecated use `GetJobsProjectJobsCode$inboundSchema` instead. */
  export const inboundSchema = GetJobsProjectJobsCode$inboundSchema;
  /** @deprecated use `GetJobsProjectJobsCode$outboundSchema` instead. */
  export const outboundSchema = GetJobsProjectJobsCode$outboundSchema;
}

/** @internal */
export const GetJobsProjectJobsCategory$inboundSchema: z.ZodNativeEnum<
  typeof GetJobsProjectJobsCategory
> = z.nativeEnum(GetJobsProjectJobsCategory);

/** @internal */
export const GetJobsProjectJobsCategory$outboundSchema: z.ZodNativeEnum<
  typeof GetJobsProjectJobsCategory
> = GetJobsProjectJobsCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsProjectJobsCategory$ {
  /** @deprecated use `GetJobsProjectJobsCategory$inboundSchema` instead. */
  export const inboundSchema = GetJobsProjectJobsCategory$inboundSchema;
  /** @deprecated use `GetJobsProjectJobsCategory$outboundSchema` instead. */
  export const outboundSchema = GetJobsProjectJobsCategory$outboundSchema;
}

/** @internal */
export const GetJobsProjectJobsResponseResponseBody$inboundSchema: z.ZodType<
  GetJobsProjectJobsResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetJobsProjectJobsCode$inboundSchema,
  category: GetJobsProjectJobsCategory$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetJobsProjectJobsResponseResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetJobsProjectJobsResponseResponseBody$Outbound = {
  code: string;
  category: string;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/** @internal */
export const GetJobsProjectJobsResponseResponseBody$outboundSchema: z.ZodType<
  GetJobsProjectJobsResponseResponseBody$Outbound,
  z.ZodTypeDef,
  GetJobsProjectJobsResponseResponseBody
> = z.instanceof(GetJobsProjectJobsResponseResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    code: GetJobsProjectJobsCode$outboundSchema,
    category: GetJobsProjectJobsCategory$outboundSchema,
    message: z.string(),
    retirable: z.boolean(),
    details: z.any().optional(),
    correlationId: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsProjectJobsResponseResponseBody$ {
  /** @deprecated use `GetJobsProjectJobsResponseResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetJobsProjectJobsResponseResponseBody$inboundSchema;
  /** @deprecated use `GetJobsProjectJobsResponseResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetJobsProjectJobsResponseResponseBody$outboundSchema;
  /** @deprecated use `GetJobsProjectJobsResponseResponseBody$Outbound` instead. */
  export type Outbound = GetJobsProjectJobsResponseResponseBody$Outbound;
}

/** @internal */
export const GetJobsCode$inboundSchema: z.ZodNativeEnum<typeof GetJobsCode> = z
  .nativeEnum(GetJobsCode);

/** @internal */
export const GetJobsCode$outboundSchema: z.ZodNativeEnum<typeof GetJobsCode> =
  GetJobsCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsCode$ {
  /** @deprecated use `GetJobsCode$inboundSchema` instead. */
  export const inboundSchema = GetJobsCode$inboundSchema;
  /** @deprecated use `GetJobsCode$outboundSchema` instead. */
  export const outboundSchema = GetJobsCode$outboundSchema;
}

/** @internal */
export const GetJobsCategory$inboundSchema: z.ZodNativeEnum<
  typeof GetJobsCategory
> = z.nativeEnum(GetJobsCategory);

/** @internal */
export const GetJobsCategory$outboundSchema: z.ZodNativeEnum<
  typeof GetJobsCategory
> = GetJobsCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsCategory$ {
  /** @deprecated use `GetJobsCategory$inboundSchema` instead. */
  export const inboundSchema = GetJobsCategory$inboundSchema;
  /** @deprecated use `GetJobsCategory$outboundSchema` instead. */
  export const outboundSchema = GetJobsCategory$outboundSchema;
}

/** @internal */
export const GetJobsProjectJobsResponseBody$inboundSchema: z.ZodType<
  GetJobsProjectJobsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: GetJobsCode$inboundSchema,
  category: GetJobsCategory$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetJobsProjectJobsResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetJobsProjectJobsResponseBody$Outbound = {
  code: string;
  category: string;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/** @internal */
export const GetJobsProjectJobsResponseBody$outboundSchema: z.ZodType<
  GetJobsProjectJobsResponseBody$Outbound,
  z.ZodTypeDef,
  GetJobsProjectJobsResponseBody
> = z.instanceof(GetJobsProjectJobsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    code: GetJobsCode$outboundSchema,
    category: GetJobsCategory$outboundSchema,
    message: z.string(),
    retirable: z.boolean(),
    details: z.any().optional(),
    correlationId: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsProjectJobsResponseBody$ {
  /** @deprecated use `GetJobsProjectJobsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetJobsProjectJobsResponseBody$inboundSchema;
  /** @deprecated use `GetJobsProjectJobsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetJobsProjectJobsResponseBody$outboundSchema;
  /** @deprecated use `GetJobsProjectJobsResponseBody$Outbound` instead. */
  export type Outbound = GetJobsProjectJobsResponseBody$Outbound;
}

/** @internal */
export const Code$inboundSchema: z.ZodNativeEnum<typeof Code> = z.nativeEnum(
  Code,
);

/** @internal */
export const Code$outboundSchema: z.ZodNativeEnum<typeof Code> =
  Code$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Code$ {
  /** @deprecated use `Code$inboundSchema` instead. */
  export const inboundSchema = Code$inboundSchema;
  /** @deprecated use `Code$outboundSchema` instead. */
  export const outboundSchema = Code$outboundSchema;
}

/** @internal */
export const Category$inboundSchema: z.ZodNativeEnum<typeof Category> = z
  .nativeEnum(Category);

/** @internal */
export const Category$outboundSchema: z.ZodNativeEnum<typeof Category> =
  Category$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Category$ {
  /** @deprecated use `Category$inboundSchema` instead. */
  export const inboundSchema = Category$inboundSchema;
  /** @deprecated use `Category$outboundSchema` instead. */
  export const outboundSchema = Category$outboundSchema;
}

/** @internal */
export const GetJobsResponseBody$inboundSchema: z.ZodType<
  GetJobsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: Code$inboundSchema,
  category: Category$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new GetJobsResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type GetJobsResponseBody$Outbound = {
  code: string;
  category: string;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/** @internal */
export const GetJobsResponseBody$outboundSchema: z.ZodType<
  GetJobsResponseBody$Outbound,
  z.ZodTypeDef,
  GetJobsResponseBody
> = z.instanceof(GetJobsResponseBody)
  .transform(v => v.data$)
  .pipe(z.object({
    code: Code$outboundSchema,
    category: Category$outboundSchema,
    message: z.string(),
    retirable: z.boolean(),
    details: z.any().optional(),
    correlationId: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetJobsResponseBody$ {
  /** @deprecated use `GetJobsResponseBody$inboundSchema` instead. */
  export const inboundSchema = GetJobsResponseBody$inboundSchema;
  /** @deprecated use `GetJobsResponseBody$outboundSchema` instead. */
  export const outboundSchema = GetJobsResponseBody$outboundSchema;
  /** @deprecated use `GetJobsResponseBody$Outbound` instead. */
  export type Outbound = GetJobsResponseBody$Outbound;
}
