/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { ClosedEnum } from "../../types/enums.js";
import { IntunedClientError } from "./intunedclienterror.js";

/**
 * The requested resource was not found
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#not-found} - Find more info here
 */
export const PauseJobProjectJobsResponseCode = {
  NotFound: "not-found",
} as const;
/**
 * The requested resource was not found
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#not-found} - Find more info here
 */
export type PauseJobProjectJobsResponseCode = ClosedEnum<
  typeof PauseJobProjectJobsResponseCode
>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const PauseJobProjectJobsResponseCategory = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type PauseJobProjectJobsResponseCategory = ClosedEnum<
  typeof PauseJobProjectJobsResponseCategory
>;

/**
 * Not Found
 */
export type PauseJobProjectJobsResponseResponseBodyData = {
  /**
   * The requested resource was not found
   */
  code: PauseJobProjectJobsResponseCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobProjectJobsResponseCategory;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Not Found
 */
export class PauseJobProjectJobsResponseResponseBody
  extends IntunedClientError
{
  /**
   * The requested resource was not found
   */
  code: PauseJobProjectJobsResponseCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobProjectJobsResponseCategory;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: PauseJobProjectJobsResponseResponseBodyData;

  constructor(
    err: PauseJobProjectJobsResponseResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "PauseJobProjectJobsResponseResponseBody";
  }
}

/**
 * The request requires user authentication
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#unauthorized} - Find more info here
 */
export const PauseJobProjectJobsCode = {
  Unauthorized: "unauthorized",
} as const;
/**
 * The request requires user authentication
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#unauthorized} - Find more info here
 */
export type PauseJobProjectJobsCode = ClosedEnum<
  typeof PauseJobProjectJobsCode
>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const PauseJobProjectJobsCategory = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type PauseJobProjectJobsCategory = ClosedEnum<
  typeof PauseJobProjectJobsCategory
>;

/**
 * Unauthorized
 */
export type PauseJobProjectJobsResponseBodyData = {
  /**
   * The request requires user authentication
   */
  code: PauseJobProjectJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobProjectJobsCategory;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Unauthorized
 */
export class PauseJobProjectJobsResponseBody extends IntunedClientError {
  /**
   * The request requires user authentication
   */
  code: PauseJobProjectJobsCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobProjectJobsCategory;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: PauseJobProjectJobsResponseBodyData;

  constructor(
    err: PauseJobProjectJobsResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "PauseJobProjectJobsResponseBody";
  }
}

/**
 * The request is invalid or malformed
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#bad-request} - Find more info here
 */
export const PauseJobCode = {
  BadRequest: "bad-request",
} as const;
/**
 * The request is invalid or malformed
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#bad-request} - Find more info here
 */
export type PauseJobCode = ClosedEnum<typeof PauseJobCode>;

/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export const PauseJobCategory = {
  User: "user",
} as const;
/**
 * Errors caused by user actions or input
 *
 * @see {@link https://docs.intunedhq.com/docs/support/errors#user} - Find more info here
 */
export type PauseJobCategory = ClosedEnum<typeof PauseJobCategory>;

/**
 * Bad Request
 */
export type PauseJobResponseBodyData = {
  /**
   * The request is invalid or malformed
   */
  code: PauseJobCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobCategory;
  message: string;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;
};

/**
 * Bad Request
 */
export class PauseJobResponseBody extends IntunedClientError {
  /**
   * The request is invalid or malformed
   */
  code: PauseJobCode;
  /**
   * Errors caused by user actions or input
   */
  category: PauseJobCategory;
  retirable: boolean;
  details?: any | undefined;
  correlationId: string;

  /** The original data that was passed to this error instance. */
  data$: PauseJobResponseBodyData;

  constructor(
    err: PauseJobResponseBodyData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.message || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.code = err.code;
    this.category = err.category;
    this.retirable = err.retirable;
    if (err.details != null) this.details = err.details;
    this.correlationId = err.correlationId;

    this.name = "PauseJobResponseBody";
  }
}

/** @internal */
export const PauseJobProjectJobsResponseCode$inboundSchema: z.ZodNativeEnum<
  typeof PauseJobProjectJobsResponseCode
> = z.nativeEnum(PauseJobProjectJobsResponseCode);

/** @internal */
export const PauseJobProjectJobsResponseCategory$inboundSchema: z.ZodNativeEnum<
  typeof PauseJobProjectJobsResponseCategory
> = z.nativeEnum(PauseJobProjectJobsResponseCategory);

/** @internal */
export const PauseJobProjectJobsResponseResponseBody$inboundSchema: z.ZodType<
  PauseJobProjectJobsResponseResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: PauseJobProjectJobsResponseCode$inboundSchema,
  category: PauseJobProjectJobsResponseCategory$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PauseJobProjectJobsResponseResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PauseJobProjectJobsCode$inboundSchema: z.ZodNativeEnum<
  typeof PauseJobProjectJobsCode
> = z.nativeEnum(PauseJobProjectJobsCode);

/** @internal */
export const PauseJobProjectJobsCategory$inboundSchema: z.ZodNativeEnum<
  typeof PauseJobProjectJobsCategory
> = z.nativeEnum(PauseJobProjectJobsCategory);

/** @internal */
export const PauseJobProjectJobsResponseBody$inboundSchema: z.ZodType<
  PauseJobProjectJobsResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: PauseJobProjectJobsCode$inboundSchema,
  category: PauseJobProjectJobsCategory$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PauseJobProjectJobsResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export const PauseJobCode$inboundSchema: z.ZodNativeEnum<typeof PauseJobCode> =
  z.nativeEnum(PauseJobCode);

/** @internal */
export const PauseJobCategory$inboundSchema: z.ZodNativeEnum<
  typeof PauseJobCategory
> = z.nativeEnum(PauseJobCategory);

/** @internal */
export const PauseJobResponseBody$inboundSchema: z.ZodType<
  PauseJobResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  code: PauseJobCode$inboundSchema,
  category: PauseJobCategory$inboundSchema,
  message: z.string(),
  retirable: z.boolean(),
  details: z.any().optional(),
  correlationId: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new PauseJobResponseBody(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });
