/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SDKHooks } from "../hooks";
import { SDKOptions, serverURLFromOptions } from "../lib/config";
import { HTTPClient } from "../lib/http";
import { ClientSDK } from "../lib/sdks";
import { Jobs } from "./jobs";
import { Queues } from "./queues";
import { Run } from "./run";

export class Project extends ClientSDK {
    private readonly options$: SDKOptions & { hooks?: SDKHooks };

    constructor(options: SDKOptions = {}) {
        const opt = options as unknown;
        let hooks: SDKHooks;
        if (
            typeof opt === "object" &&
            opt != null &&
            "hooks" in opt &&
            opt.hooks instanceof SDKHooks
        ) {
            hooks = opt.hooks;
        } else {
            hooks = new SDKHooks();
        }

        super({
            client: options.httpClient || new HTTPClient(),
            baseURL: serverURLFromOptions(options),
            hooks,
        });

        this.options$ = { ...options, hooks };
        void this.options$;
    }

    private _jobs?: Jobs;
    get jobs(): Jobs {
        return (this._jobs ??= new Jobs(this.options$));
    }

    private _queues?: Queues;
    get queues(): Queues {
        return (this._queues ??= new Queues(this.options$));
    }

    private _run?: Run;
    get run(): Run {
        return (this._run ??= new Run(this.options$));
    }
}
