/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { projectRunResult } from "../funcs/projectRunResult.js";
import { projectRunStart } from "../funcs/projectRunStart.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Run extends ClientSDK {
  /**
   * Run API - Start
   *
   * @remarks
   * Start a Run for a Project.
   */
  async start(
    projectName: string,
    requestBody: operations.RunApiStartRequestBody,
    options?: RequestOptions,
  ): Promise<operations.RunApiStartResponseBody> {
    return unwrapAsync(projectRunStart(
      this,
      projectName,
      requestBody,
      options,
    ));
  }

  /**
   * Run API - Result
   *
   * @remarks
   * Get Run result.
   */
  async result(
    projectName: string,
    runId: string,
    options?: RequestOptions,
  ): Promise<operations.RunApiResultResponseBody> {
    return unwrapAsync(projectRunResult(
      this,
      projectName,
      runId,
      options,
    ));
  }
}
