workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    intunedClientApi:
        inputs:
            - location: ../docs/_resources/openapi/jobs.yaml
            - location: ../docs/_resources/openapi/queues.yaml
            - location: ../docs/_resources/openapi/files.yaml
            - location: ../docs/_resources/openapi/run.yaml
        registry:
            location: registry.speakeasyapi.dev/intuned/intuned/intuned-client-api
targets:
    my-first-target:
        target: typescript
        source: intunedClientApi
        codeSamples:
          output:  ../docs/_resources/openapi/generated/codeSamples.yaml

