/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type AddItemGlobals = {
    /**
     * Workspace Id.
     */
    workspaceId?: string | undefined;
    /**
     * Project Name.
     */
    projectName?: string | undefined;
};

export type AddItemRequest = {
    /**
     * Project name
     */
    projectName?: string | undefined;
    /**
     * Queue ID
     */
    queueId: string;
    /**
     * queue item
     */
    queueItem?: components.QueueItem | undefined;
};

export enum Status {
    Queued = "queued",
}

/**
 * Item appended
 */
export type AddItemResponseBody = {
    runId?: string | undefined;
    status?: Status | undefined;
};

export type AddItemResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Item appended
     */
    object?: AddItemResponseBody | undefined;
};

/** @internal */
export namespace AddItemGlobals$ {
    export const inboundSchema: z.ZodType<AddItemGlobals, z.ZodTypeDef, unknown> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });

    export type Outbound = {
        workspaceId?: string | undefined;
        projectName?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddItemGlobals> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });
}

/** @internal */
export namespace AddItemRequest$ {
    export const inboundSchema: z.ZodType<AddItemRequest, z.ZodTypeDef, unknown> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            QueueItem: components.QueueItem$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                ...(v.QueueItem === undefined ? null : { queueItem: v.QueueItem }),
            };
        });

    export type Outbound = {
        projectName?: string | undefined;
        queueId: string;
        QueueItem?: components.QueueItem$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddItemRequest> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            queueItem: components.QueueItem$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                ...(v.queueItem === undefined ? null : { QueueItem: v.queueItem }),
            };
        });
}

/** @internal */
export namespace Status$ {
    export const inboundSchema = z.nativeEnum(Status);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace AddItemResponseBody$ {
    export const inboundSchema: z.ZodType<AddItemResponseBody, z.ZodTypeDef, unknown> = z
        .object({
            runId: z.string().optional(),
            status: Status$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.runId === undefined ? null : { runId: v.runId }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });

    export type Outbound = {
        runId?: string | undefined;
        status?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddItemResponseBody> = z
        .object({
            runId: z.string().optional(),
            status: Status$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.runId === undefined ? null : { runId: v.runId }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });
}

/** @internal */
export namespace AddItemResponse$ {
    export const inboundSchema: z.ZodType<AddItemResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddItemResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddItemResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddItemResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddItemResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
