/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type AddRepeatItemGlobals = {
    /**
     * Workspace Id.
     */
    workspaceId?: string | undefined;
    /**
     * Project Name.
     */
    projectName?: string | undefined;
};

export type AddRepeatItemRequest = {
    /**
     * Project name
     */
    projectName?: string | undefined;
    /**
     * Queue ID
     */
    queueId: string;
    /**
     * queue repeat item
     */
    queueRepeatItemInput?: components.QueueRepeatItemInput | undefined;
};

export enum AddRepeatItemStatus {
    RepeatableItemCreated = "repeatable item created",
}

/**
 * Item appended
 */
export type AddRepeatItemResponseBody = {
    id?: string | undefined;
    status?: AddRepeatItemStatus | undefined;
};

export type AddRepeatItemResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Item appended
     */
    object?: AddRepeatItemResponseBody | undefined;
};

/** @internal */
export namespace AddRepeatItemGlobals$ {
    export const inboundSchema: z.ZodType<AddRepeatItemGlobals, z.ZodTypeDef, unknown> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });

    export type Outbound = {
        workspaceId?: string | undefined;
        projectName?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddRepeatItemGlobals> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });
}

/** @internal */
export namespace AddRepeatItemRequest$ {
    export const inboundSchema: z.ZodType<AddRepeatItemRequest, z.ZodTypeDef, unknown> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            QueueRepeatItemInput: components.QueueRepeatItemInput$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                ...(v.QueueRepeatItemInput === undefined
                    ? null
                    : { queueRepeatItemInput: v.QueueRepeatItemInput }),
            };
        });

    export type Outbound = {
        projectName?: string | undefined;
        queueId: string;
        QueueRepeatItemInput?: components.QueueRepeatItemInput$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddRepeatItemRequest> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            queueRepeatItemInput: components.QueueRepeatItemInput$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                ...(v.queueRepeatItemInput === undefined
                    ? null
                    : { QueueRepeatItemInput: v.queueRepeatItemInput }),
            };
        });
}

/** @internal */
export namespace AddRepeatItemStatus$ {
    export const inboundSchema = z.nativeEnum(AddRepeatItemStatus);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace AddRepeatItemResponseBody$ {
    export const inboundSchema: z.ZodType<AddRepeatItemResponseBody, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string().optional(),
            status: AddRepeatItemStatus$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });

    export type Outbound = {
        id?: string | undefined;
        status?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddRepeatItemResponseBody> = z
        .object({
            id: z.string().optional(),
            status: AddRepeatItemStatus$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });
}

/** @internal */
export namespace AddRepeatItemResponse$ {
    export const inboundSchema: z.ZodType<AddRepeatItemResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => AddRepeatItemResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: AddRepeatItemResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AddRepeatItemResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => AddRepeatItemResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
