/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

export type CreateQueueGlobals = {
    /**
     * Your workspace ID. [How to find it](/docs/guides/platform/how-to-get-a-workspace-id)?
     */
    workspaceId?: string | undefined;
};

export type CreateQueueRequest = {
    /**
     * Your project name. It is the name you provide when creating a project.
     */
    projectName: string;
    /**
     * create queue request
     */
    queueInput: components.QueueInput;
};

/** @internal */
export namespace CreateQueueGlobals$ {
    export const inboundSchema: z.ZodType<CreateQueueGlobals, z.ZodTypeDef, unknown> = z.object({
        workspaceId: z.string().optional(),
    });

    export type Outbound = {
        workspaceId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateQueueGlobals> = z.object({
        workspaceId: z.string().optional(),
    });
}

/** @internal */
export namespace CreateQueueRequest$ {
    export const inboundSchema: z.ZodType<CreateQueueRequest, z.ZodTypeDef, unknown> = z
        .object({
            projectName: z.string(),
            QueueInput: components.QueueInput$.inboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                QueueInput: "queueInput",
            });
        });

    export type Outbound = {
        projectName: string;
        QueueInput: components.QueueInput$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreateQueueRequest> = z
        .object({
            projectName: z.string(),
            queueInput: components.QueueInput$.outboundSchema,
        })
        .transform((v) => {
            return remap$(v, {
                queueInput: "QueueInput",
            });
        });
}
