/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type DeleteQueueItemGlobals = {
    /**
     * Workspace Id.
     */
    workspaceId?: string | undefined;
    /**
     * Project Name.
     */
    projectName?: string | undefined;
};

export type DeleteQueueItemRequest = {
    /**
     * Project name
     */
    projectName?: string | undefined;
    /**
     * Queue ID
     */
    queueId: string;
    /**
     * Queue item run ID
     */
    itemRunId: string;
};

/**
 * Queue item deleted
 */
export type DeleteQueueItemResponseBody = {
    runId?: string | undefined;
};

export type DeleteQueueItemResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Queue item deleted
     */
    object?: DeleteQueueItemResponseBody | undefined;
};

/** @internal */
export namespace DeleteQueueItemGlobals$ {
    export const inboundSchema: z.ZodType<DeleteQueueItemGlobals, z.ZodTypeDef, unknown> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });

    export type Outbound = {
        workspaceId?: string | undefined;
        projectName?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteQueueItemGlobals> = z
        .object({
            workspaceId: z.string().optional(),
            projectName: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.workspaceId === undefined ? null : { workspaceId: v.workspaceId }),
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
            };
        });
}

/** @internal */
export namespace DeleteQueueItemRequest$ {
    export const inboundSchema: z.ZodType<DeleteQueueItemRequest, z.ZodTypeDef, unknown> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            itemRunId: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                itemRunId: v.itemRunId,
            };
        });

    export type Outbound = {
        projectName?: string | undefined;
        queueId: string;
        itemRunId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteQueueItemRequest> = z
        .object({
            projectName: z.string().optional(),
            queueId: z.string(),
            itemRunId: z.string(),
        })
        .transform((v) => {
            return {
                ...(v.projectName === undefined ? null : { projectName: v.projectName }),
                queueId: v.queueId,
                itemRunId: v.itemRunId,
            };
        });
}

/** @internal */
export namespace DeleteQueueItemResponseBody$ {
    export const inboundSchema: z.ZodType<DeleteQueueItemResponseBody, z.ZodTypeDef, unknown> = z
        .object({
            runId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.runId === undefined ? null : { runId: v.runId }),
            };
        });

    export type Outbound = {
        runId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteQueueItemResponseBody> = z
        .object({
            runId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.runId === undefined ? null : { runId: v.runId }),
            };
        });
}

/** @internal */
export namespace DeleteQueueItemResponse$ {
    export const inboundSchema: z.ZodType<DeleteQueueItemResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            object: z.lazy(() => DeleteQueueItemResponseBody$.inboundSchema).optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        object?: DeleteQueueItemResponseBody$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, DeleteQueueItemResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            object: z.lazy(() => DeleteQueueItemResponseBody$.outboundSchema).optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.object === undefined ? null : { object: v.object }),
            };
        });
}
