/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type GetJobsGlobals = {
    /**
     * Your workspace ID. [How to find it](https://docs.intunedhq.com/docs/management/workspace#finding-your-workspace-id)?
     */
    workspaceId: string;
};

export type GetJobsRequest = {
    /**
     * Your project name. It is the name you provide when creating a project.
     */
    projectName: string;
};

export type GetJobsResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Array of jobs
     */
    getJobs?: Array<components.Job> | undefined;
};

/** @internal */
export namespace GetJobsGlobals$ {
    export const inboundSchema: z.ZodType<GetJobsGlobals, z.ZodTypeDef, unknown> = z.object({
        workspaceId: z.string(),
    });

    export type Outbound = {
        workspaceId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetJobsGlobals> = z.object({
        workspaceId: z.string(),
    });
}

/** @internal */
export namespace GetJobsRequest$ {
    export const inboundSchema: z.ZodType<GetJobsRequest, z.ZodTypeDef, unknown> = z.object({
        projectName: z.string(),
    });

    export type Outbound = {
        projectName: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetJobsRequest> = z.object({
        projectName: z.string(),
    });
}

/** @internal */
export namespace GetJobsResponse$ {
    export const inboundSchema: z.ZodType<GetJobsResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            GetJobs: z.array(components.Job$.inboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                GetJobs: "getJobs",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        GetJobs?: Array<components.Job$.Outbound> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetJobsResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            getJobs: z.array(components.Job$.outboundSchema).optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                getJobs: "GetJobs",
            });
        });
}
