/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type GetJobRunsGlobals = {
    /**
     * Your workspace ID. [How to find it](/docs/guides/platform/how-to-get-a-workspace-id)?
     */
    workspaceId?: string | undefined;
};

export type GetJobRunsRequest = {
    /**
     * Your project name. It is the name you provide when creating a project.
     */
    projectName: string;
    /**
     * Your job ID. It is the ID of the job you provide when creating it.
     */
    jobId: string;
};

/** @internal */
export namespace GetJobRunsGlobals$ {
    export const inboundSchema: z.ZodType<GetJobRunsGlobals, z.ZodTypeDef, unknown> = z.object({
        workspaceId: z.string().optional(),
    });

    export type Outbound = {
        workspaceId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetJobRunsGlobals> = z.object({
        workspaceId: z.string().optional(),
    });
}

/** @internal */
export namespace GetJobRunsRequest$ {
    export const inboundSchema: z.ZodType<GetJobRunsRequest, z.ZodTypeDef, unknown> = z.object({
        projectName: z.string(),
        jobId: z.string(),
    });

    export type Outbound = {
        projectName: string;
        jobId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GetJobRunsRequest> = z.object({
        projectName: z.string(),
        jobId: z.string(),
    });
}
