/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../lib/primitives";
import * as components from "../components";
import * as z from "zod";

export type PauseJobGlobals = {
    /**
     * Your workspace ID. [How to find it](https://docs.intunedhq.com/docs/management/workspace#finding-your-workspace-id)?
     */
    workspaceId: string;
};

export type PauseJobRequest = {
    /**
     * Your project name. It is the name you provide when creating a project.
     */
    projectName: string;
    /**
     * Your job ID. It is the ID of the job you provide when creating it.
     */
    jobId: string;
};

export type PauseJobResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Successfully paused job
     */
    pauseJob?: components.PauseJob | undefined;
};

/** @internal */
export namespace PauseJobGlobals$ {
    export const inboundSchema: z.ZodType<PauseJobGlobals, z.ZodTypeDef, unknown> = z.object({
        workspaceId: z.string(),
    });

    export type Outbound = {
        workspaceId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PauseJobGlobals> = z.object({
        workspaceId: z.string(),
    });
}

/** @internal */
export namespace PauseJobRequest$ {
    export const inboundSchema: z.ZodType<PauseJobRequest, z.ZodTypeDef, unknown> = z.object({
        projectName: z.string(),
        jobId: z.string(),
    });

    export type Outbound = {
        projectName: string;
        jobId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PauseJobRequest> = z.object({
        projectName: z.string(),
        jobId: z.string(),
    });
}

/** @internal */
export namespace PauseJobResponse$ {
    export const inboundSchema: z.ZodType<PauseJobResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            PauseJob: components.PauseJob$.inboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                HttpMeta: "httpMeta",
                PauseJob: "pauseJob",
            });
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        PauseJob?: components.PauseJob$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, PauseJobResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            pauseJob: components.PauseJob$.outboundSchema.optional(),
        })
        .transform((v) => {
            return remap$(v, {
                httpMeta: "HttpMeta",
                pauseJob: "PauseJob",
            });
        });
}
