/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../components";
import * as z from "zod";

export type RunApiResultGlobals = {
    /**
     * Workspace ID
     */
    workspaceId: string;
};

export type RunApiResultRequest = {
    /**
     * Project name
     */
    projectName: string;
    /**
     * Run ID
     */
    operationId: string;
};

export type RunApiResultResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Result of the run operation. Could be pending, completed or failed.
     */
    asyncResultResponse?: components.AsyncResultResponse | undefined;
};

/** @internal */
export namespace RunApiResultGlobals$ {
    export const inboundSchema: z.ZodType<RunApiResultGlobals, z.ZodTypeDef, unknown> = z
        .object({
            workspaceId: z.string(),
        })
        .transform((v) => {
            return {
                workspaceId: v.workspaceId,
            };
        });

    export type Outbound = {
        workspaceId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunApiResultGlobals> = z
        .object({
            workspaceId: z.string(),
        })
        .transform((v) => {
            return {
                workspaceId: v.workspaceId,
            };
        });
}

/** @internal */
export namespace RunApiResultRequest$ {
    export const inboundSchema: z.ZodType<RunApiResultRequest, z.ZodTypeDef, unknown> = z
        .object({
            projectName: z.string(),
            operationId: z.string(),
        })
        .transform((v) => {
            return {
                projectName: v.projectName,
                operationId: v.operationId,
            };
        });

    export type Outbound = {
        projectName: string;
        operationId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunApiResultRequest> = z
        .object({
            projectName: z.string(),
            operationId: z.string(),
        })
        .transform((v) => {
            return {
                projectName: v.projectName,
                operationId: v.operationId,
            };
        });
}

/** @internal */
export namespace RunApiResultResponse$ {
    export const inboundSchema: z.ZodType<RunApiResultResponse, z.ZodTypeDef, unknown> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            AsyncResultResponse: components.AsyncResultResponse$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.AsyncResultResponse === undefined
                    ? null
                    : { asyncResultResponse: v.AsyncResultResponse }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        AsyncResultResponse?: components.AsyncResultResponse$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunApiResultResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            asyncResultResponse: components.AsyncResultResponse$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.asyncResultResponse === undefined
                    ? null
                    : { AsyncResultResponse: v.asyncResultResponse }),
            };
        });
}
