/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAuthSessionResultGlobals = {
  /**
   * Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?
   */
  workspaceId?: string | undefined;
};

export type UpdateAuthSessionResultRequest = {
  /**
   * Your project name. It is the name you provide when creating a project.
   */
  projectName: string;
  /**
   * Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
   */
  authSessionId: string;
  /**
   * The ID for the requested auth session creation operation. This is obtained from the start request.
   */
  operationId: string;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus =
  {
    Failed: "failed",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus
  >;

/**
 * Optional error code for more specific error identification
 */
export const UpdateAuthSessionResultResponseBodyCode = {
  InternalServerError: "internal-server-error",
  ScriptProcessCrashed: "script-process-crashed",
  Unexpected: "unexpected",
  ScriptExecutionException: "script-execution-exception",
  ScriptNoValidOutputReceived: "script-no-valid-output-received",
  ResultTooBigError: "result-too-big-error",
  ScriptTimeout: "script-timeout",
  ScriptUnexpectedError: "script-unexpected-error",
  AuthCheckFailed: "auth-check-failed",
  AllAttemptsFailed: "all-attempts-failed",
  CheckAttemptsFailed: "check-attempts-failed",
  CreateAttemptsFailed: "create-attempts-failed",
  PostCreateCheckAttemptsFailed: "post-create-check-attempts-failed",
  ApiAttemptsFailed: "api-attempts-failed",
  OnepasswordIntegrationError: "onepassword-integration-error",
  JobRunTerminated: "job-run-terminated",
} as const;
/**
 * Optional error code for more specific error identification
 */
export type UpdateAuthSessionResultResponseBodyCode = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyCode
>;

export const UpdateAuthSessionResultResponseBodyCategory = {
  Infrastructure: "infrastructure",
  Execution: "execution",
  Auth: "auth",
  User: "user",
  Billing: "billing",
} as const;
export type UpdateAuthSessionResultResponseBodyCategory = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyCategory
>;

export type UpdateAuthSessionResultResponseBodyError = {
  /**
   * Error message describing the failure
   */
  message: string;
  /**
   * Optional error code for more specific error identification
   */
  code?: UpdateAuthSessionResultResponseBodyCode | undefined;
  category: UpdateAuthSessionResultResponseBodyCategory;
  retirable?: boolean | undefined;
  /**
   * Optional URL to documentation for this error
   */
  docUrl?: string | undefined;
  /**
   * Optional correlation ID for tracing the error in logs
   */
  correlationId?: string | undefined;
  details?: any | undefined;
};

export type ResponseBodyFailed = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus;
  message: string;
  error: UpdateAuthSessionResultResponseBodyError;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status =
  {
    InProgress: "in_progress",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status
  >;

export type ResponseBodyInProgress = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status;
  /**
   * Unique identifier for the run, nanoId of 21 characters
   */
  runId: string;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus =
  {
    Canceled: "canceled",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus
  >;

export const UpdateAuthSessionResultResponseBodyType = {
  AuthSessionValidateDependencyFailed:
    "auth-session-validate-dependency-failed",
  Terminated: "terminated",
  JobRunPaused: "job-run-paused",
  JobRunTerminated: "job-run-terminated",
  FailedToInitializeJobRun: "failed-to-initialize-job-run",
  ApiAccessDisabled: "api-access-disabled",
} as const;
export type UpdateAuthSessionResultResponseBodyType = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyType
>;

export type UpdateAuthSessionResultResponseBodyReason = {
  type: UpdateAuthSessionResultResponseBodyType;
  message: string;
  /**
   * Optional URL to documentation for this error
   */
  docUrl?: string | undefined;
  details?: any | undefined;
};

export type ResponseBodyCanceled = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus;
  message: string;
  reason: UpdateAuthSessionResultResponseBodyReason;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus =
  {
    Pending: "pending",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus
  >;

export type ResponseBodyPending = {
  status: UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus;
};

export const UpdateAuthSessionResultResponseBodyStatus = {
  Done: "done",
} as const;
export type UpdateAuthSessionResultResponseBodyStatus = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyStatus
>;

export type ResponseBodyDone = {
  status: UpdateAuthSessionResultResponseBodyStatus;
  /**
   * The unique identifier for the authentication session
   */
  authSessionId: string;
};

/**
 * Auth session update result
 */
export type UpdateAuthSessionResultResponseBody =
  | ResponseBodyCanceled
  | ResponseBodyFailed
  | ResponseBodyDone
  | ResponseBodyInProgress
  | ResponseBodyPending;

/** @internal */
export const UpdateAuthSessionResultGlobals$inboundSchema: z.ZodType<
  UpdateAuthSessionResultGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: z.string().optional(),
});

/** @internal */
export type UpdateAuthSessionResultGlobals$Outbound = {
  workspaceId?: string | undefined;
};

/** @internal */
export const UpdateAuthSessionResultGlobals$outboundSchema: z.ZodType<
  UpdateAuthSessionResultGlobals$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultGlobals
> = z.object({
  workspaceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultGlobals$ {
  /** @deprecated use `UpdateAuthSessionResultGlobals$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResultGlobals$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultGlobals$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResultGlobals$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultGlobals$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultGlobals$Outbound;
}

export function updateAuthSessionResultGlobalsToJSON(
  updateAuthSessionResultGlobals: UpdateAuthSessionResultGlobals,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultGlobals$outboundSchema.parse(
      updateAuthSessionResultGlobals,
    ),
  );
}

export function updateAuthSessionResultGlobalsFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAuthSessionResultGlobals, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAuthSessionResultGlobals$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAuthSessionResultGlobals' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultRequest$inboundSchema: z.ZodType<
  UpdateAuthSessionResultRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  authSessionId: z.string(),
  operationId: z.string(),
});

/** @internal */
export type UpdateAuthSessionResultRequest$Outbound = {
  projectName: string;
  authSessionId: string;
  operationId: string;
};

/** @internal */
export const UpdateAuthSessionResultRequest$outboundSchema: z.ZodType<
  UpdateAuthSessionResultRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultRequest
> = z.object({
  projectName: z.string(),
  authSessionId: z.string(),
  operationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultRequest$ {
  /** @deprecated use `UpdateAuthSessionResultRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResultRequest$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResultRequest$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultRequest$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultRequest$Outbound;
}

export function updateAuthSessionResultRequestToJSON(
  updateAuthSessionResultRequest: UpdateAuthSessionResultRequest,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultRequest$outboundSchema.parse(
      updateAuthSessionResultRequest,
    ),
  );
}

export function updateAuthSessionResultRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAuthSessionResultRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateAuthSessionResultRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAuthSessionResultRequest' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$outboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus
  > =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$outboundSchema;
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyCode$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCode> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyCode);

/** @internal */
export const UpdateAuthSessionResultResponseBodyCode$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCode> =
    UpdateAuthSessionResultResponseBodyCode$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyCode$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyCode$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyCode$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyCode$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyCode$outboundSchema;
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyCategory$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCategory> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyCategory);

/** @internal */
export const UpdateAuthSessionResultResponseBodyCategory$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCategory> =
    UpdateAuthSessionResultResponseBodyCategory$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyCategory$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyCategory$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyCategory$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyCategory$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyCategory$outboundSchema;
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyError$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: UpdateAuthSessionResultResponseBodyCode$inboundSchema.optional(),
  category: UpdateAuthSessionResultResponseBodyCategory$inboundSchema,
  retirable: z.boolean().default(false),
  doc_url: z.string().optional(),
  correlation_id: z.string().optional(),
  details: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
    "correlation_id": "correlationId",
  });
});

/** @internal */
export type UpdateAuthSessionResultResponseBodyError$Outbound = {
  message: string;
  code?: string | undefined;
  category: string;
  retirable: boolean;
  doc_url?: string | undefined;
  correlation_id?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const UpdateAuthSessionResultResponseBodyError$outboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyError$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultResponseBodyError
> = z.object({
  message: z.string(),
  code: UpdateAuthSessionResultResponseBodyCode$outboundSchema.optional(),
  category: UpdateAuthSessionResultResponseBodyCategory$outboundSchema,
  retirable: z.boolean().default(false),
  docUrl: z.string().optional(),
  correlationId: z.string().optional(),
  details: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    docUrl: "doc_url",
    correlationId: "correlation_id",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyError$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyError$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyError$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyError$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyError$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyError$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultResponseBodyError$Outbound;
}

export function updateAuthSessionResultResponseBodyErrorToJSON(
  updateAuthSessionResultResponseBodyError:
    UpdateAuthSessionResultResponseBodyError,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultResponseBodyError$outboundSchema.parse(
      updateAuthSessionResultResponseBodyError,
    ),
  );
}

export function updateAuthSessionResultResponseBodyErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyError' from JSON`,
  );
}

/** @internal */
export const ResponseBodyFailed$inboundSchema: z.ZodType<
  ResponseBodyFailed,
  z.ZodTypeDef,
  unknown
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema,
  message: z.string(),
  error: z.lazy(() => UpdateAuthSessionResultResponseBodyError$inboundSchema),
});

/** @internal */
export type ResponseBodyFailed$Outbound = {
  status: string;
  message: string;
  error: UpdateAuthSessionResultResponseBodyError$Outbound;
};

/** @internal */
export const ResponseBodyFailed$outboundSchema: z.ZodType<
  ResponseBodyFailed$Outbound,
  z.ZodTypeDef,
  ResponseBodyFailed
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$outboundSchema,
  message: z.string(),
  error: z.lazy(() => UpdateAuthSessionResultResponseBodyError$outboundSchema),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyFailed$ {
  /** @deprecated use `ResponseBodyFailed$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyFailed$inboundSchema;
  /** @deprecated use `ResponseBodyFailed$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyFailed$outboundSchema;
  /** @deprecated use `ResponseBodyFailed$Outbound` instead. */
  export type Outbound = ResponseBodyFailed$Outbound;
}

export function responseBodyFailedToJSON(
  responseBodyFailed: ResponseBodyFailed,
): string {
  return JSON.stringify(
    ResponseBodyFailed$outboundSchema.parse(responseBodyFailed),
  );
}

export function responseBodyFailedFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyFailed, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBodyFailed$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyFailed' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$outboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status
  > =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$outboundSchema;
}

/** @internal */
export const ResponseBodyInProgress$inboundSchema: z.ZodType<
  ResponseBodyInProgress,
  z.ZodTypeDef,
  unknown
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema,
  runId: z.string(),
});

/** @internal */
export type ResponseBodyInProgress$Outbound = {
  status: string;
  runId: string;
};

/** @internal */
export const ResponseBodyInProgress$outboundSchema: z.ZodType<
  ResponseBodyInProgress$Outbound,
  z.ZodTypeDef,
  ResponseBodyInProgress
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$outboundSchema,
  runId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyInProgress$ {
  /** @deprecated use `ResponseBodyInProgress$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyInProgress$inboundSchema;
  /** @deprecated use `ResponseBodyInProgress$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyInProgress$outboundSchema;
  /** @deprecated use `ResponseBodyInProgress$Outbound` instead. */
  export type Outbound = ResponseBodyInProgress$Outbound;
}

export function responseBodyInProgressToJSON(
  responseBodyInProgress: ResponseBodyInProgress,
): string {
  return JSON.stringify(
    ResponseBodyInProgress$outboundSchema.parse(responseBodyInProgress),
  );
}

export function responseBodyInProgressFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyInProgress, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBodyInProgress$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyInProgress' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$outboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus
  > =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$outboundSchema;
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyType$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyType> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyType);

/** @internal */
export const UpdateAuthSessionResultResponseBodyType$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyType> =
    UpdateAuthSessionResultResponseBodyType$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyType$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyType$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyType$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyType$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyType$outboundSchema;
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyReason$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyReason,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: UpdateAuthSessionResultResponseBodyType$inboundSchema,
  message: z.string(),
  doc_url: z.string().optional(),
  details: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
  });
});

/** @internal */
export type UpdateAuthSessionResultResponseBodyReason$Outbound = {
  type: string;
  message: string;
  doc_url?: string | undefined;
  details?: any | undefined;
};

/** @internal */
export const UpdateAuthSessionResultResponseBodyReason$outboundSchema:
  z.ZodType<
    UpdateAuthSessionResultResponseBodyReason$Outbound,
    z.ZodTypeDef,
    UpdateAuthSessionResultResponseBodyReason
  > = z.object({
    type: UpdateAuthSessionResultResponseBodyType$outboundSchema,
    message: z.string(),
    docUrl: z.string().optional(),
    details: z.any().optional(),
  }).transform((v) => {
    return remap$(v, {
      docUrl: "doc_url",
    });
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyReason$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyReason$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyReason$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyReason$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyReason$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyReason$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultResponseBodyReason$Outbound;
}

export function updateAuthSessionResultResponseBodyReasonToJSON(
  updateAuthSessionResultResponseBodyReason:
    UpdateAuthSessionResultResponseBodyReason,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultResponseBodyReason$outboundSchema.parse(
      updateAuthSessionResultResponseBodyReason,
    ),
  );
}

export function updateAuthSessionResultResponseBodyReasonFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyReason,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyReason$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyReason' from JSON`,
  );
}

/** @internal */
export const ResponseBodyCanceled$inboundSchema: z.ZodType<
  ResponseBodyCanceled,
  z.ZodTypeDef,
  unknown
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema,
  message: z.string(),
  reason: z.lazy(() => UpdateAuthSessionResultResponseBodyReason$inboundSchema),
});

/** @internal */
export type ResponseBodyCanceled$Outbound = {
  status: string;
  message: string;
  reason: UpdateAuthSessionResultResponseBodyReason$Outbound;
};

/** @internal */
export const ResponseBodyCanceled$outboundSchema: z.ZodType<
  ResponseBodyCanceled$Outbound,
  z.ZodTypeDef,
  ResponseBodyCanceled
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$outboundSchema,
  message: z.string(),
  reason: z.lazy(() =>
    UpdateAuthSessionResultResponseBodyReason$outboundSchema
  ),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyCanceled$ {
  /** @deprecated use `ResponseBodyCanceled$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyCanceled$inboundSchema;
  /** @deprecated use `ResponseBodyCanceled$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyCanceled$outboundSchema;
  /** @deprecated use `ResponseBodyCanceled$Outbound` instead. */
  export type Outbound = ResponseBodyCanceled$Outbound;
}

export function responseBodyCanceledToJSON(
  responseBodyCanceled: ResponseBodyCanceled,
): string {
  return JSON.stringify(
    ResponseBodyCanceled$outboundSchema.parse(responseBodyCanceled),
  );
}

export function responseBodyCanceledFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyCanceled, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBodyCanceled$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyCanceled' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$outboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus
  > =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$outboundSchema;
}

/** @internal */
export const ResponseBodyPending$inboundSchema: z.ZodType<
  ResponseBodyPending,
  z.ZodTypeDef,
  unknown
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema,
});

/** @internal */
export type ResponseBodyPending$Outbound = {
  status: string;
};

/** @internal */
export const ResponseBodyPending$outboundSchema: z.ZodType<
  ResponseBodyPending$Outbound,
  z.ZodTypeDef,
  ResponseBodyPending
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyPending$ {
  /** @deprecated use `ResponseBodyPending$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyPending$inboundSchema;
  /** @deprecated use `ResponseBodyPending$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyPending$outboundSchema;
  /** @deprecated use `ResponseBodyPending$Outbound` instead. */
  export type Outbound = ResponseBodyPending$Outbound;
}

export function responseBodyPendingToJSON(
  responseBodyPending: ResponseBodyPending,
): string {
  return JSON.stringify(
    ResponseBodyPending$outboundSchema.parse(responseBodyPending),
  );
}

export function responseBodyPendingFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyPending, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBodyPending$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyPending' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyStatus$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyStatus> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyStatus);

/** @internal */
export const UpdateAuthSessionResultResponseBodyStatus$outboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyStatus> =
    UpdateAuthSessionResultResponseBodyStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBodyStatus$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBodyStatus$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBodyStatus$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBodyStatus$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBodyStatus$outboundSchema;
}

/** @internal */
export const ResponseBodyDone$inboundSchema: z.ZodType<
  ResponseBodyDone,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: UpdateAuthSessionResultResponseBodyStatus$inboundSchema,
  authSessionId: z.string(),
});

/** @internal */
export type ResponseBodyDone$Outbound = {
  status: string;
  authSessionId: string;
};

/** @internal */
export const ResponseBodyDone$outboundSchema: z.ZodType<
  ResponseBodyDone$Outbound,
  z.ZodTypeDef,
  ResponseBodyDone
> = z.object({
  status: UpdateAuthSessionResultResponseBodyStatus$outboundSchema,
  authSessionId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ResponseBodyDone$ {
  /** @deprecated use `ResponseBodyDone$inboundSchema` instead. */
  export const inboundSchema = ResponseBodyDone$inboundSchema;
  /** @deprecated use `ResponseBodyDone$outboundSchema` instead. */
  export const outboundSchema = ResponseBodyDone$outboundSchema;
  /** @deprecated use `ResponseBodyDone$Outbound` instead. */
  export type Outbound = ResponseBodyDone$Outbound;
}

export function responseBodyDoneToJSON(
  responseBodyDone: ResponseBodyDone,
): string {
  return JSON.stringify(
    ResponseBodyDone$outboundSchema.parse(responseBodyDone),
  );
}

export function responseBodyDoneFromJSON(
  jsonString: string,
): SafeParseResult<ResponseBodyDone, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ResponseBodyDone$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ResponseBodyDone' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBody$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => ResponseBodyCanceled$inboundSchema),
  z.lazy(() => ResponseBodyFailed$inboundSchema),
  z.lazy(() => ResponseBodyDone$inboundSchema),
  z.lazy(() => ResponseBodyInProgress$inboundSchema),
  z.lazy(() => ResponseBodyPending$inboundSchema),
]);

/** @internal */
export type UpdateAuthSessionResultResponseBody$Outbound =
  | ResponseBodyCanceled$Outbound
  | ResponseBodyFailed$Outbound
  | ResponseBodyDone$Outbound
  | ResponseBodyInProgress$Outbound
  | ResponseBodyPending$Outbound;

/** @internal */
export const UpdateAuthSessionResultResponseBody$outboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBody$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultResponseBody
> = z.union([
  z.lazy(() => ResponseBodyCanceled$outboundSchema),
  z.lazy(() => ResponseBodyFailed$outboundSchema),
  z.lazy(() => ResponseBodyDone$outboundSchema),
  z.lazy(() => ResponseBodyInProgress$outboundSchema),
  z.lazy(() => ResponseBodyPending$outboundSchema),
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultResponseBody$ {
  /** @deprecated use `UpdateAuthSessionResultResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    UpdateAuthSessionResultResponseBody$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    UpdateAuthSessionResultResponseBody$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultResponseBody$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultResponseBody$Outbound;
}

export function updateAuthSessionResultResponseBodyToJSON(
  updateAuthSessionResultResponseBody: UpdateAuthSessionResultResponseBody,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultResponseBody$outboundSchema.parse(
      updateAuthSessionResultResponseBody,
    ),
  );
}

export function updateAuthSessionResultResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAuthSessionResultResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAuthSessionResultResponseBody' from JSON`,
  );
}
