/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdateAuthSessionResultGlobals = {
  /**
   * Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?
   */
  workspaceId?: string | undefined;
};

export type UpdateAuthSessionResultRequest = {
  /**
   * Your project name. It is the name you provide when creating a project.
   */
  projectName: string;
  /**
   * Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
   */
  authSessionId: string;
  /**
   * The ID for the operation. This is obtained from the start request.
   */
  operationId: string;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus =
  {
    Failed: "failed",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus
  >;

/**
 * Optional error code for more specific error identification
 */
export const UpdateAuthSessionResultResponseBodyCode = {
  InternalServerError: "internal-server-error",
  ScriptProcessCrashed: "script-process-crashed",
  Unexpected: "unexpected",
  ScriptExecutionException: "script-execution-exception",
  ScriptNoValidOutputReceived: "script-no-valid-output-received",
  ResultTooBigError: "result-too-big-error",
  ScriptTimeout: "script-timeout",
  ScriptUnexpectedError: "script-unexpected-error",
  AuthCheckFailed: "auth-check-failed",
  AllAttemptsFailed: "all-attempts-failed",
  CheckAttemptsFailed: "check-attempts-failed",
  CreateAttemptsFailed: "create-attempts-failed",
  PostCreateCheckAttemptsFailed: "post-create-check-attempts-failed",
  ApiAttemptsFailed: "api-attempts-failed",
  OnepasswordIntegrationError: "onepassword-integration-error",
  JobRunTerminated: "job-run-terminated",
} as const;
/**
 * Optional error code for more specific error identification
 */
export type UpdateAuthSessionResultResponseBodyCode = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyCode
>;

export const UpdateAuthSessionResultResponseBodyCategory = {
  Infrastructure: "infrastructure",
  Execution: "execution",
  Auth: "auth",
  User: "user",
  Billing: "billing",
} as const;
export type UpdateAuthSessionResultResponseBodyCategory = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyCategory
>;

export type UpdateAuthSessionResultResponseBodyError = {
  /**
   * Error message describing the failure
   */
  message: string;
  /**
   * Optional error code for more specific error identification
   */
  code?: UpdateAuthSessionResultResponseBodyCode | undefined;
  category: UpdateAuthSessionResultResponseBodyCategory;
  retirable?: boolean | undefined;
  /**
   * Optional URL to documentation for this error
   */
  docUrl?: string | undefined;
  /**
   * Optional correlation ID for tracing the error in logs
   */
  correlationId?: string | undefined;
  details?: any | undefined;
};

export type UpdateAuthSessionResultResponseBodyFailed = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus;
  message: string;
  error: UpdateAuthSessionResultResponseBodyError;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status =
  {
    InProgress: "in_progress",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status
  >;

export type UpdateAuthSessionResultResponseBodyInProgress = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status;
  /**
   * Unique identifier for the run, nanoId of 21 characters
   */
  runId: string;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus =
  {
    Canceled: "canceled",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus
  >;

export const UpdateAuthSessionResultResponseBodyType = {
  AuthSessionValidateDependencyFailed:
    "auth-session-validate-dependency-failed",
  Terminated: "terminated",
  JobRunPaused: "job-run-paused",
  JobRunTerminated: "job-run-terminated",
  FailedToInitializeJobRun: "failed-to-initialize-job-run",
  ApiAccessDisabled: "api-access-disabled",
  CancelledUserAction: "cancelled-user-action",
} as const;
export type UpdateAuthSessionResultResponseBodyType = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyType
>;

export type UpdateAuthSessionResultResponseBodyReason = {
  type: UpdateAuthSessionResultResponseBodyType;
  message: string;
  /**
   * Optional URL to documentation for this error
   */
  docUrl?: string | undefined;
  details?: any | undefined;
};

export type UpdateAuthSessionResultResponseBodyCanceled = {
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus;
  message: string;
  reason: UpdateAuthSessionResultResponseBodyReason;
};

export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus =
  {
    Pending: "pending",
  } as const;
export type UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus =
  ClosedEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus
  >;

export type UpdateAuthSessionResultResponseBodyPending = {
  status: UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus;
};

export const UpdateAuthSessionResultResponseBodyStatus = {
  Done: "done",
} as const;
export type UpdateAuthSessionResultResponseBodyStatus = ClosedEnum<
  typeof UpdateAuthSessionResultResponseBodyStatus
>;

export type UpdateAuthSessionResultResponseBodyDone = {
  status: UpdateAuthSessionResultResponseBodyStatus;
  /**
   * The unique identifier for the authentication session
   */
  authSessionId: string;
};

/**
 * AuthSession update result
 */
export type UpdateAuthSessionResultResponseBody =
  | UpdateAuthSessionResultResponseBodyCanceled
  | UpdateAuthSessionResultResponseBodyFailed
  | UpdateAuthSessionResultResponseBodyDone
  | UpdateAuthSessionResultResponseBodyInProgress
  | UpdateAuthSessionResultResponseBodyPending;

/** @internal */
export type UpdateAuthSessionResultRequest$Outbound = {
  projectName: string;
  authSessionId: string;
  operationId: string;
};

/** @internal */
export const UpdateAuthSessionResultRequest$outboundSchema: z.ZodType<
  UpdateAuthSessionResultRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultRequest
> = z.object({
  projectName: z.string(),
  authSessionId: z.string(),
  operationId: z.string(),
});

export function updateAuthSessionResultRequestToJSON(
  updateAuthSessionResultRequest: UpdateAuthSessionResultRequest,
): string {
  return JSON.stringify(
    UpdateAuthSessionResultRequest$outboundSchema.parse(
      updateAuthSessionResultRequest,
    ),
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyCode$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCode> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyCode);

/** @internal */
export const UpdateAuthSessionResultResponseBodyCategory$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyCategory> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyCategory);

/** @internal */
export const UpdateAuthSessionResultResponseBodyError$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyError,
  z.ZodTypeDef,
  unknown
> = z.object({
  message: z.string(),
  code: UpdateAuthSessionResultResponseBodyCode$inboundSchema.optional(),
  category: UpdateAuthSessionResultResponseBodyCategory$inboundSchema,
  retirable: z.boolean().default(false),
  doc_url: z.string().optional(),
  correlation_id: z.string().optional(),
  details: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
    "correlation_id": "correlationId",
  });
});

export function updateAuthSessionResultResponseBodyErrorFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyError,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyError$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyError' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyFailed$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyFailed,
  z.ZodTypeDef,
  unknown
> = z.object({
  status:
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200ApplicationJSONStatus$inboundSchema,
  message: z.string(),
  error: z.lazy(() => UpdateAuthSessionResultResponseBodyError$inboundSchema),
});

export function updateAuthSessionResultResponseBodyFailedFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyFailed,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyFailed$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyFailed' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyInProgress$inboundSchema:
  z.ZodType<
    UpdateAuthSessionResultResponseBodyInProgress,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status:
      UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponse200Status$inboundSchema,
    runId: z.string(),
  });

export function updateAuthSessionResultResponseBodyInProgressFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyInProgress,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyInProgress$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyInProgress' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyType$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyType> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyType);

/** @internal */
export const UpdateAuthSessionResultResponseBodyReason$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyReason,
  z.ZodTypeDef,
  unknown
> = z.object({
  type: UpdateAuthSessionResultResponseBodyType$inboundSchema,
  message: z.string(),
  doc_url: z.string().optional(),
  details: z.any().optional(),
}).transform((v) => {
  return remap$(v, {
    "doc_url": "docUrl",
  });
});

export function updateAuthSessionResultResponseBodyReasonFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyReason,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyReason$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyReason' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyCanceled$inboundSchema:
  z.ZodType<
    UpdateAuthSessionResultResponseBodyCanceled,
    z.ZodTypeDef,
    unknown
  > = z.object({
    status:
      UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateResponseStatus$inboundSchema,
    message: z.string(),
    reason: z.lazy(() =>
      UpdateAuthSessionResultResponseBodyReason$inboundSchema
    ),
  });

export function updateAuthSessionResultResponseBodyCanceledFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyCanceled,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyCanceled$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyCanceled' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema:
  z.ZodNativeEnum<
    typeof UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus
  > = z.nativeEnum(
    UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus,
  );

/** @internal */
export const UpdateAuthSessionResultResponseBodyPending$inboundSchema:
  z.ZodType<UpdateAuthSessionResultResponseBodyPending, z.ZodTypeDef, unknown> =
    z.object({
      status:
        UpdateAuthSessionResultResponseBodyProjectAuthSessionsUpdateStatus$inboundSchema,
    });

export function updateAuthSessionResultResponseBodyPendingFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyPending,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyPending$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyPending' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBodyStatus$inboundSchema:
  z.ZodNativeEnum<typeof UpdateAuthSessionResultResponseBodyStatus> = z
    .nativeEnum(UpdateAuthSessionResultResponseBodyStatus);

/** @internal */
export const UpdateAuthSessionResultResponseBodyDone$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBodyDone,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: UpdateAuthSessionResultResponseBodyStatus$inboundSchema,
  authSessionId: z.string(),
});

export function updateAuthSessionResultResponseBodyDoneFromJSON(
  jsonString: string,
): SafeParseResult<
  UpdateAuthSessionResultResponseBodyDone,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBodyDone$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'UpdateAuthSessionResultResponseBodyDone' from JSON`,
  );
}

/** @internal */
export const UpdateAuthSessionResultResponseBody$inboundSchema: z.ZodType<
  UpdateAuthSessionResultResponseBody,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => UpdateAuthSessionResultResponseBodyCanceled$inboundSchema),
  z.lazy(() => UpdateAuthSessionResultResponseBodyFailed$inboundSchema),
  z.lazy(() => UpdateAuthSessionResultResponseBodyDone$inboundSchema),
  z.lazy(() => UpdateAuthSessionResultResponseBodyInProgress$inboundSchema),
  z.lazy(() => UpdateAuthSessionResultResponseBodyPending$inboundSchema),
]);

export function updateAuthSessionResultResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateAuthSessionResultResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      UpdateAuthSessionResultResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateAuthSessionResultResponseBody' from JSON`,
  );
}
