/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type UpdateAuthSessionResumeGlobals = {
  /**
   * Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?
   */
  workspaceId?: string | undefined;
};

export type UpdateAuthSessionResumeRequest = {
  /**
   * Your project name. It is the name you provide when creating a project.
   */
  projectName: string;
  /**
   * The ID for the requested auth session creation operation. This is obtained from the start request.
   */
  operationId: string;
  /**
   * resume authentication session creation request
   */
  authSessionCreateResume: components.AuthSessionCreateResume;
};

/** @internal */
export const UpdateAuthSessionResumeGlobals$inboundSchema: z.ZodType<
  UpdateAuthSessionResumeGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: z.string().optional(),
});

/** @internal */
export type UpdateAuthSessionResumeGlobals$Outbound = {
  workspaceId?: string | undefined;
};

/** @internal */
export const UpdateAuthSessionResumeGlobals$outboundSchema: z.ZodType<
  UpdateAuthSessionResumeGlobals$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResumeGlobals
> = z.object({
  workspaceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResumeGlobals$ {
  /** @deprecated use `UpdateAuthSessionResumeGlobals$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResumeGlobals$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResumeGlobals$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResumeGlobals$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResumeGlobals$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResumeGlobals$Outbound;
}

/** @internal */
export const UpdateAuthSessionResumeRequest$inboundSchema: z.ZodType<
  UpdateAuthSessionResumeRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  operationId: z.string(),
  AuthSessionCreateResume: components.AuthSessionCreateResume$inboundSchema,
}).transform((v) => {
  return remap$(v, {
    "AuthSessionCreateResume": "authSessionCreateResume",
  });
});

/** @internal */
export type UpdateAuthSessionResumeRequest$Outbound = {
  projectName: string;
  operationId: string;
  AuthSessionCreateResume: components.AuthSessionCreateResume$Outbound;
};

/** @internal */
export const UpdateAuthSessionResumeRequest$outboundSchema: z.ZodType<
  UpdateAuthSessionResumeRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResumeRequest
> = z.object({
  projectName: z.string(),
  operationId: z.string(),
  authSessionCreateResume: components.AuthSessionCreateResume$outboundSchema,
}).transform((v) => {
  return remap$(v, {
    authSessionCreateResume: "AuthSessionCreateResume",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResumeRequest$ {
  /** @deprecated use `UpdateAuthSessionResumeRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResumeRequest$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResumeRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResumeRequest$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResumeRequest$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResumeRequest$Outbound;
}
