/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type UpdateAuthSessionResultGlobals = {
  /**
   * Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?
   */
  workspaceId?: string | undefined;
};

export type UpdateAuthSessionResultRequest = {
  /**
   * Your project name. It is the name you provide when creating a project.
   */
  projectName: string;
  /**
   * The ID for the requested auth session creation operation. This is obtained from the start request.
   */
  operationId: string;
};

/** @internal */
export const UpdateAuthSessionResultGlobals$inboundSchema: z.ZodType<
  UpdateAuthSessionResultGlobals,
  z.ZodTypeDef,
  unknown
> = z.object({
  workspaceId: z.string().optional(),
});

/** @internal */
export type UpdateAuthSessionResultGlobals$Outbound = {
  workspaceId?: string | undefined;
};

/** @internal */
export const UpdateAuthSessionResultGlobals$outboundSchema: z.ZodType<
  UpdateAuthSessionResultGlobals$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultGlobals
> = z.object({
  workspaceId: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultGlobals$ {
  /** @deprecated use `UpdateAuthSessionResultGlobals$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResultGlobals$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultGlobals$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResultGlobals$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultGlobals$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultGlobals$Outbound;
}

/** @internal */
export const UpdateAuthSessionResultRequest$inboundSchema: z.ZodType<
  UpdateAuthSessionResultRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  projectName: z.string(),
  operationId: z.string(),
});

/** @internal */
export type UpdateAuthSessionResultRequest$Outbound = {
  projectName: string;
  operationId: string;
};

/** @internal */
export const UpdateAuthSessionResultRequest$outboundSchema: z.ZodType<
  UpdateAuthSessionResultRequest$Outbound,
  z.ZodTypeDef,
  UpdateAuthSessionResultRequest
> = z.object({
  projectName: z.string(),
  operationId: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateAuthSessionResultRequest$ {
  /** @deprecated use `UpdateAuthSessionResultRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateAuthSessionResultRequest$inboundSchema;
  /** @deprecated use `UpdateAuthSessionResultRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateAuthSessionResultRequest$outboundSchema;
  /** @deprecated use `UpdateAuthSessionResultRequest$Outbound` instead. */
  export type Outbound = UpdateAuthSessionResultRequest$Outbound;
}
