/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ValidateAuthSessionStartGlobals = {
  /**
   * Your workspace ID. [How to find it](/docs/guides/general/how-to-get-a-workspace-id)?
   */
  workspaceId?: string | undefined;
};

/**
 * Validate auth session input schema
 */
export type ValidateAuthSessionStartRequestBody = {
  /**
   * If true, the auth session will be automatically recreated if the check fails.
   */
  autoRecreate?: boolean | undefined;
  /**
   * Number of attempts to check the validity of the auth session before recreating it.
   */
  checkAttempts?: number | undefined;
  /**
   * Number of attempts to create a new auth session if the current one is invalid or expired.
   */
  createAttempts?: number | undefined;
  /**
   * Proxy URL to be used for the API call. This is optional and can be used to route the API call through a proxy server.
   */
  proxy?: string | null | undefined;
  /**
   * Timeout for the API request in seconds. Default is 10 minutes (600 seconds).
   */
  requestTimeout?: number | undefined;
};

export type ValidateAuthSessionStartRequest = {
  /**
   * Your project name. It is the name you provide when creating a project.
   */
  projectName: string;
  /**
   * Authentication session ID. You can obtain it from the Auth Sessions tab in your project details.
   */
  authSessionId: string;
  /**
   * Validate auth session input schema
   */
  requestBody: ValidateAuthSessionStartRequestBody;
};

export const ValidateAuthSessionStartStatus = {
  Pending: "pending",
} as const;
export type ValidateAuthSessionStartStatus = ClosedEnum<
  typeof ValidateAuthSessionStartStatus
>;

/**
 * Validate auth session operation started
 */
export type ValidateAuthSessionStartResponseBody = {
  status: ValidateAuthSessionStartStatus;
  operationId: string;
};

/** @internal */
export type ValidateAuthSessionStartRequestBody$Outbound = {
  autoRecreate: boolean;
  checkAttempts: number;
  createAttempts: number;
  proxy?: string | null | undefined;
  requestTimeout: number;
};

/** @internal */
export const ValidateAuthSessionStartRequestBody$outboundSchema: z.ZodType<
  ValidateAuthSessionStartRequestBody$Outbound,
  z.ZodTypeDef,
  ValidateAuthSessionStartRequestBody
> = z.object({
  autoRecreate: z.boolean().default(true),
  checkAttempts: z.number().int().default(3),
  createAttempts: z.number().int().default(3),
  proxy: z.nullable(z.string()).optional(),
  requestTimeout: z.number().int().default(600),
});

export function validateAuthSessionStartRequestBodyToJSON(
  validateAuthSessionStartRequestBody: ValidateAuthSessionStartRequestBody,
): string {
  return JSON.stringify(
    ValidateAuthSessionStartRequestBody$outboundSchema.parse(
      validateAuthSessionStartRequestBody,
    ),
  );
}

/** @internal */
export type ValidateAuthSessionStartRequest$Outbound = {
  projectName: string;
  authSessionId: string;
  RequestBody: ValidateAuthSessionStartRequestBody$Outbound;
};

/** @internal */
export const ValidateAuthSessionStartRequest$outboundSchema: z.ZodType<
  ValidateAuthSessionStartRequest$Outbound,
  z.ZodTypeDef,
  ValidateAuthSessionStartRequest
> = z.object({
  projectName: z.string(),
  authSessionId: z.string(),
  requestBody: z.lazy(() => ValidateAuthSessionStartRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

export function validateAuthSessionStartRequestToJSON(
  validateAuthSessionStartRequest: ValidateAuthSessionStartRequest,
): string {
  return JSON.stringify(
    ValidateAuthSessionStartRequest$outboundSchema.parse(
      validateAuthSessionStartRequest,
    ),
  );
}

/** @internal */
export const ValidateAuthSessionStartStatus$inboundSchema: z.ZodNativeEnum<
  typeof ValidateAuthSessionStartStatus
> = z.nativeEnum(ValidateAuthSessionStartStatus);

/** @internal */
export const ValidateAuthSessionStartResponseBody$inboundSchema: z.ZodType<
  ValidateAuthSessionStartResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  status: ValidateAuthSessionStartStatus$inboundSchema,
  operationId: z.string(),
});

export function validateAuthSessionStartResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<ValidateAuthSessionStartResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ValidateAuthSessionStartResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ValidateAuthSessionStartResponseBody' from JSON`,
  );
}
