/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * The status of the asynchronous operation
 */
export enum AsyncRunPendingResponseStatus {
    Pending = "pending",
}

export type AsyncRunPendingResponse = {
    /**
     * The status of the asynchronous operation
     */
    status?: AsyncRunPendingResponseStatus | undefined;
    /**
     * The operation ID
     */
    operationId?: string | undefined;
};

/** @internal */
export namespace AsyncRunPendingResponseStatus$ {
    export const inboundSchema = z.nativeEnum(AsyncRunPendingResponseStatus);
    export const outboundSchema = inboundSchema;
}

/** @internal */
export namespace AsyncRunPendingResponse$ {
    export const inboundSchema: z.ZodType<AsyncRunPendingResponse, z.ZodTypeDef, unknown> = z
        .object({
            status: AsyncRunPendingResponseStatus$.inboundSchema.optional(),
            operationId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.operationId === undefined ? null : { operationId: v.operationId }),
            };
        });

    export type Outbound = {
        status?: string | undefined;
        operationId?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AsyncRunPendingResponse> = z
        .object({
            status: AsyncRunPendingResponseStatus$.outboundSchema.optional(),
            operationId: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
                ...(v.operationId === undefined ? null : { operationId: v.operationId }),
            };
        });
}
