/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

/**
 * Status of auth session creation operation
 */
export const AuthSessionCreatePendingResultStatus = {
    Pending: "pending",
} as const;
/**
 * Status of auth session creation operation
 */
export type AuthSessionCreatePendingResultStatus = ClosedEnum<
    typeof AuthSessionCreatePendingResultStatus
>;

/**
 * Auth session create pending
 */
export type AuthSessionCreatePendingResult = {
    /**
     * Status of auth session creation operation
     */
    status: AuthSessionCreatePendingResultStatus;
};

/** @internal */
export namespace AuthSessionCreatePendingResultStatus$ {
    export const inboundSchema: z.ZodNativeEnum<typeof AuthSessionCreatePendingResultStatus> =
        z.nativeEnum(AuthSessionCreatePendingResultStatus);
    export const outboundSchema: z.ZodNativeEnum<typeof AuthSessionCreatePendingResultStatus> =
        inboundSchema;
}

/** @internal */
export namespace AuthSessionCreatePendingResult$ {
    export const inboundSchema: z.ZodType<AuthSessionCreatePendingResult, z.ZodTypeDef, unknown> =
        z.object({
            status: AuthSessionCreatePendingResultStatus$.inboundSchema,
        });

    export type Outbound = {
        status: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AuthSessionCreatePendingResult> =
        z.object({
            status: AuthSessionCreatePendingResultStatus$.outboundSchema,
        });
}
