/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Auth session configurations
 */
export type AuthSession = {
    /**
     * The ID of the auth session to be used
     */
    id: string;
};

/** @internal */
export namespace AuthSession$ {
    export const inboundSchema: z.ZodType<AuthSession, z.ZodTypeDef, unknown> = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AuthSession> = z.object({
        id: z.string(),
    });
}
