/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

export type AuthSessionInfo = {
    id: string;
    name?: string | undefined;
};

/** @internal */
export namespace AuthSessionInfo$ {
    export const inboundSchema: z.ZodType<AuthSessionInfo, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                id: v.id,
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });

    export type Outbound = {
        id: string;
        name?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, AuthSessionInfo> = z
        .object({
            id: z.string(),
            name: z.string().optional(),
        })
        .transform((v) => {
            return {
                id: v.id,
                ...(v.name === undefined ? null : { name: v.name }),
            };
        });
}
