/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Auth session recorder create instance
 */
export type CreateRecorderAuthSessionRequest = {
    /**
     * Auth session id
     */
    id?: string | undefined;
    /**
     * Proxy URL following this format `http://username:password@domain:port`
     */
    proxy?: string | undefined;
};

/** @internal */
export const CreateRecorderAuthSessionRequest$inboundSchema: z.ZodType<
    CreateRecorderAuthSessionRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    id: z.string().optional(),
    proxy: z.string().optional(),
});

/** @internal */
export type CreateRecorderAuthSessionRequest$Outbound = {
    id?: string | undefined;
    proxy?: string | undefined;
};

/** @internal */
export const CreateRecorderAuthSessionRequest$outboundSchema: z.ZodType<
    CreateRecorderAuthSessionRequest$Outbound,
    z.ZodTypeDef,
    CreateRecorderAuthSessionRequest
> = z.object({
    id: z.string().optional(),
    proxy: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateRecorderAuthSessionRequest$ {
    /** @deprecated use `CreateRecorderAuthSessionRequest$inboundSchema` instead. */
    export const inboundSchema = CreateRecorderAuthSessionRequest$inboundSchema;
    /** @deprecated use `CreateRecorderAuthSessionRequest$outboundSchema` instead. */
    export const outboundSchema = CreateRecorderAuthSessionRequest$outboundSchema;
    /** @deprecated use `CreateRecorderAuthSessionRequest$Outbound` instead. */
    export type Outbound = CreateRecorderAuthSessionRequest$Outbound;
}
