/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { FileT, FileT$inboundSchema, FileT$Outbound, FileT$outboundSchema } from "./file.js";
import * as z from "zod";

export type GeneralExtractRequest = {
    file: FileT;
};

/** @internal */
export const GeneralExtractRequest$inboundSchema: z.ZodType<
    GeneralExtractRequest,
    z.ZodTypeDef,
    unknown
> = z.object({
    file: FileT$inboundSchema,
});

/** @internal */
export type GeneralExtractRequest$Outbound = {
    file: FileT$Outbound;
};

/** @internal */
export const GeneralExtractRequest$outboundSchema: z.ZodType<
    GeneralExtractRequest$Outbound,
    z.ZodTypeDef,
    GeneralExtractRequest
> = z.object({
    file: FileT$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GeneralExtractRequest$ {
    /** @deprecated use `GeneralExtractRequest$inboundSchema` instead. */
    export const inboundSchema = GeneralExtractRequest$inboundSchema;
    /** @deprecated use `GeneralExtractRequest$outboundSchema` instead. */
    export const outboundSchema = GeneralExtractRequest$outboundSchema;
    /** @deprecated use `GeneralExtractRequest$Outbound` instead. */
    export type Outbound = GeneralExtractRequest$Outbound;
}
