/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { FileT, FileT$ } from "./file";
import * as z from "zod";

export type GeneralExtractRequest = {
    file: FileT;
};

/** @internal */
export namespace GeneralExtractRequest$ {
    export const inboundSchema: z.ZodType<GeneralExtractRequest, z.ZodTypeDef, unknown> = z.object({
        file: FileT$.inboundSchema,
    });

    export type Outbound = {
        file: FileT$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, GeneralExtractRequest> =
        z.object({
            file: FileT$.outboundSchema,
        });
}
