/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AuthSession, AuthSession$ } from "./authsession";
import { JobConfiguration, JobConfiguration$ } from "./jobconfiguration";
import { JobPayload, JobPayload$ } from "./jobpayload";
import { JobSchedule, JobSchedule$ } from "./jobschedule";
import { JobSink, JobSink$ } from "./jobsink";
import { Proxy, Proxy$ } from "./proxy";
import * as z from "zod";

export type State = {
    status?: string | undefined;
};

export type Job = {
    id: string;
    configuration: JobConfiguration;
    sink?: JobSink | undefined;
    payload: Array<JobPayload>;
    schedule?: JobSchedule | undefined;
    authSession?: AuthSession | undefined;
    proxy?: Proxy | undefined;
    createdAt?: Date | undefined;
    nextRunTime?: Date | null | undefined;
    lastRunTime?: Date | undefined;
    state?: State | undefined;
    memo?: { [k: string]: any } | undefined;
    projectId: string;
};

/** @internal */
export namespace State$ {
    export const inboundSchema: z.ZodType<State, z.ZodTypeDef, unknown> = z
        .object({
            status: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });

    export type Outbound = {
        status?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, State> = z
        .object({
            status: z.string().optional(),
        })
        .transform((v) => {
            return {
                ...(v.status === undefined ? null : { status: v.status }),
            };
        });
}

/** @internal */
export namespace Job$ {
    export const inboundSchema: z.ZodType<Job, z.ZodTypeDef, unknown> = z
        .object({
            id: z.string(),
            configuration: JobConfiguration$.inboundSchema,
            sink: JobSink$.inboundSchema.optional(),
            payload: z.array(JobPayload$.inboundSchema),
            schedule: JobSchedule$.inboundSchema.optional(),
            authSession: AuthSession$.inboundSchema.optional(),
            proxy: Proxy$.inboundSchema.optional(),
            created_at: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            next_run_time: z
                .nullable(
                    z
                        .string()
                        .datetime({ offset: true })
                        .transform((v) => new Date(v))
                )
                .optional(),
            last_run_time: z
                .string()
                .datetime({ offset: true })
                .transform((v) => new Date(v))
                .optional(),
            state: z.lazy(() => State$.inboundSchema).optional(),
            memo: z.record(z.any()).optional(),
            projectId: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                configuration: v.configuration,
                ...(v.sink === undefined ? null : { sink: v.sink }),
                payload: v.payload,
                ...(v.schedule === undefined ? null : { schedule: v.schedule }),
                ...(v.authSession === undefined ? null : { authSession: v.authSession }),
                ...(v.proxy === undefined ? null : { proxy: v.proxy }),
                ...(v.created_at === undefined ? null : { createdAt: v.created_at }),
                ...(v.next_run_time === undefined ? null : { nextRunTime: v.next_run_time }),
                ...(v.last_run_time === undefined ? null : { lastRunTime: v.last_run_time }),
                ...(v.state === undefined ? null : { state: v.state }),
                ...(v.memo === undefined ? null : { memo: v.memo }),
                projectId: v.projectId,
            };
        });

    export type Outbound = {
        id: string;
        configuration: JobConfiguration$.Outbound;
        sink?: JobSink$.Outbound | undefined;
        payload: Array<JobPayload$.Outbound>;
        schedule?: JobSchedule$.Outbound | undefined;
        authSession?: AuthSession$.Outbound | undefined;
        proxy?: Proxy$.Outbound | undefined;
        created_at?: string | undefined;
        next_run_time?: string | null | undefined;
        last_run_time?: string | undefined;
        state?: State$.Outbound | undefined;
        memo?: { [k: string]: any } | undefined;
        projectId: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Job> = z
        .object({
            id: z.string(),
            configuration: JobConfiguration$.outboundSchema,
            sink: JobSink$.outboundSchema.optional(),
            payload: z.array(JobPayload$.outboundSchema),
            schedule: JobSchedule$.outboundSchema.optional(),
            authSession: AuthSession$.outboundSchema.optional(),
            proxy: Proxy$.outboundSchema.optional(),
            createdAt: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            nextRunTime: z.nullable(z.date().transform((v) => v.toISOString())).optional(),
            lastRunTime: z
                .date()
                .transform((v) => v.toISOString())
                .optional(),
            state: z.lazy(() => State$.outboundSchema).optional(),
            memo: z.record(z.any()).optional(),
            projectId: z.string(),
        })
        .transform((v) => {
            return {
                id: v.id,
                configuration: v.configuration,
                ...(v.sink === undefined ? null : { sink: v.sink }),
                payload: v.payload,
                ...(v.schedule === undefined ? null : { schedule: v.schedule }),
                ...(v.authSession === undefined ? null : { authSession: v.authSession }),
                ...(v.proxy === undefined ? null : { proxy: v.proxy }),
                ...(v.createdAt === undefined ? null : { created_at: v.createdAt }),
                ...(v.nextRunTime === undefined ? null : { next_run_time: v.nextRunTime }),
                ...(v.lastRunTime === undefined ? null : { last_run_time: v.lastRunTime }),
                ...(v.state === undefined ? null : { state: v.state }),
                ...(v.memo === undefined ? null : { memo: v.memo }),
                projectId: v.projectId,
            };
        });
}
