/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { WebhookAPIInfo, WebhookAPIInfo$ } from "./webhookapiinfo.js";
import * as z from "zod";

/**
 * The project details of the API
 */
export type QueueSinkResultPayloadProject = {
    /**
     * The project ID
     */
    id: string;
    /**
     * The project name
     */
    name: string;
};

/**
 * The auth session used in the run
 */
export type QueueSinkResultPayloadAuthSession = {
    /**
     * The ID of the auth session
     */
    id: string;
};

/**
 * The queue details of the run
 */
export type ProjectQueue = {
    /**
     * The queue ID
     */
    id: string;
};

/**
 * Webhook payload of queue item run result
 */
export type QueueSinkResultPayload = {
    /**
     * Webhook API info
     */
    apiInfo: WebhookAPIInfo;
    /**
     * The workspace ID of the API
     */
    workspaceId: string;
    /**
     * The project details of the API
     */
    project: QueueSinkResultPayloadProject;
    /**
     * The auth session used in the run
     */
    authSession?: QueueSinkResultPayloadAuthSession | undefined;
    /**
     * The queue details of the run
     */
    projectQueue: ProjectQueue;
};

/** @internal */
export namespace QueueSinkResultPayloadProject$ {
    export const inboundSchema: z.ZodType<QueueSinkResultPayloadProject, z.ZodTypeDef, unknown> =
        z.object({
            id: z.string(),
            name: z.string(),
        });

    export type Outbound = {
        id: string;
        name: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, QueueSinkResultPayloadProject> =
        z.object({
            id: z.string(),
            name: z.string(),
        });
}

/** @internal */
export namespace QueueSinkResultPayloadAuthSession$ {
    export const inboundSchema: z.ZodType<
        QueueSinkResultPayloadAuthSession,
        z.ZodTypeDef,
        unknown
    > = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<
        Outbound,
        z.ZodTypeDef,
        QueueSinkResultPayloadAuthSession
    > = z.object({
        id: z.string(),
    });
}

/** @internal */
export namespace ProjectQueue$ {
    export const inboundSchema: z.ZodType<ProjectQueue, z.ZodTypeDef, unknown> = z.object({
        id: z.string(),
    });

    export type Outbound = {
        id: string;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ProjectQueue> = z.object({
        id: z.string(),
    });
}

/** @internal */
export namespace QueueSinkResultPayload$ {
    export const inboundSchema: z.ZodType<QueueSinkResultPayload, z.ZodTypeDef, unknown> = z.object(
        {
            apiInfo: WebhookAPIInfo$.inboundSchema,
            workspaceId: z.string(),
            project: z.lazy(() => QueueSinkResultPayloadProject$.inboundSchema),
            authSession: z.lazy(() => QueueSinkResultPayloadAuthSession$.inboundSchema).optional(),
            projectQueue: z.lazy(() => ProjectQueue$.inboundSchema),
        }
    );

    export type Outbound = {
        apiInfo: WebhookAPIInfo$.Outbound;
        workspaceId: string;
        project: QueueSinkResultPayloadProject$.Outbound;
        authSession?: QueueSinkResultPayloadAuthSession$.Outbound | undefined;
        projectQueue: ProjectQueue$.Outbound;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, QueueSinkResultPayload> =
        z.object({
            apiInfo: WebhookAPIInfo$.outboundSchema,
            workspaceId: z.string(),
            project: z.lazy(() => QueueSinkResultPayloadProject$.outboundSchema),
            authSession: z.lazy(() => QueueSinkResultPayloadAuthSession$.outboundSchema).optional(),
            projectQueue: z.lazy(() => ProjectQueue$.outboundSchema),
        });
}
