/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { ClosedEnum } from "../../types/enums.js";
import * as z from "zod";

export const ResumeJobMessage = {
    Resumed: "Resumed",
} as const;
export type ResumeJobMessage = ClosedEnum<typeof ResumeJobMessage>;

export type ResumeJob = {
    id?: string | undefined;
    message?: ResumeJobMessage | undefined;
};

/** @internal */
export namespace ResumeJobMessage$ {
    export const inboundSchema: z.ZodNativeEnum<typeof ResumeJobMessage> =
        z.nativeEnum(ResumeJobMessage);
    export const outboundSchema: z.ZodNativeEnum<typeof ResumeJobMessage> = inboundSchema;
}

/** @internal */
export namespace ResumeJob$ {
    export const inboundSchema: z.ZodType<ResumeJob, z.ZodTypeDef, unknown> = z.object({
        id: z.string().optional(),
        message: ResumeJobMessage$.inboundSchema.optional(),
    });

    export type Outbound = {
        id?: string | undefined;
        message?: string | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, ResumeJob> = z.object({
        id: z.string().optional(),
        message: ResumeJobMessage$.outboundSchema.optional(),
    });
}
