/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * Retry policy configurations
 */
export type Retry = {
    /**
     * The maximum number of attempts to retry the API execution if it fails.
     */
    maximumAttempts: number;
};

/** @internal */
export namespace Retry$ {
    export const inboundSchema: z.ZodType<Retry, z.ZodTypeDef, unknown> = z.object({
        maximumAttempts: z.number(),
    });

    export type Outbound = {
        maximumAttempts: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Retry> = z.object({
        maximumAttempts: z.number(),
    });
}
