/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { AuthSession, AuthSession$ } from "./authsession";
import { Proxy, Proxy$ } from "./proxy";
import * as z from "zod";

export type RunProjectApiRequestRetry = {
    /**
     * The maximum number of attempts to retry the API execution if it fails.
     */
    maximumAttempts: number;
};

export type RunProjectApiRequest = {
    /**
     * The API you want to run from the project
     */
    api: string;
    /**
     * The parameters passed to the running API
     */
    parameters: { [k: string]: any };
    retry?: RunProjectApiRequestRetry | undefined;
    authSession?: AuthSession | undefined;
    proxy?: Proxy | undefined;
};

/** @internal */
export namespace RunProjectApiRequestRetry$ {
    export const inboundSchema: z.ZodType<RunProjectApiRequestRetry, z.ZodTypeDef, unknown> = z
        .object({
            maximumAttempts: z.number(),
        })
        .transform((v) => {
            return {
                maximumAttempts: v.maximumAttempts,
            };
        });

    export type Outbound = {
        maximumAttempts: number;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunProjectApiRequestRetry> = z
        .object({
            maximumAttempts: z.number(),
        })
        .transform((v) => {
            return {
                maximumAttempts: v.maximumAttempts,
            };
        });
}

/** @internal */
export namespace RunProjectApiRequest$ {
    export const inboundSchema: z.ZodType<RunProjectApiRequest, z.ZodTypeDef, unknown> = z
        .object({
            api: z.string(),
            parameters: z.record(z.any()),
            retry: z.lazy(() => RunProjectApiRequestRetry$.inboundSchema).optional(),
            authSession: AuthSession$.inboundSchema.optional(),
            proxy: Proxy$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                api: v.api,
                parameters: v.parameters,
                ...(v.retry === undefined ? null : { retry: v.retry }),
                ...(v.authSession === undefined ? null : { authSession: v.authSession }),
                ...(v.proxy === undefined ? null : { proxy: v.proxy }),
            };
        });

    export type Outbound = {
        api: string;
        parameters: { [k: string]: any };
        retry?: RunProjectApiRequestRetry$.Outbound | undefined;
        authSession?: AuthSession$.Outbound | undefined;
        proxy?: Proxy$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, RunProjectApiRequest> = z
        .object({
            api: z.string(),
            parameters: z.record(z.any()),
            retry: z.lazy(() => RunProjectApiRequestRetry$.outboundSchema).optional(),
            authSession: AuthSession$.outboundSchema.optional(),
            proxy: Proxy$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                api: v.api,
                parameters: v.parameters,
                ...(v.retry === undefined ? null : { retry: v.retry }),
                ...(v.authSession === undefined ? null : { authSession: v.authSession }),
                ...(v.proxy === undefined ? null : { proxy: v.proxy }),
            };
        });
}
